# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

linters:
  # Enable all available linters.
  # Default: false
  # enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
    - varnamelen # doesn't like one-letter var names
    - exhaustive # requires way too many switch...case statements
    - gci # couldn't get it working
    - exhaustivestruct
    - exhaustruct
    - gomnd # i like the concept but it comes up in too many places (magic numbers)
    - funlen
    - wrapcheck
    - mnd # magic numbers
    - err113 # wrapped error functions (TODO: eventually re-enable this)
    - intrange # only works in go 1.22 and later; I don't want to break earlier versions
    # - deadcode
    # - golint
    # - ifshort
    # - interfacer
    # - maligned
    # - nosnakecase
    # - scopelint
    # - structcheck
    # - varcheck

  # # Enable presets.
  # # https://golangci-lint.run/usage/linters
  # # Default: []
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  depguard:
    rules:
      # https://github.com/OpenPeeDeeP/depguard
      Main:
        files:
          - "$all"
          - "!$test"
        listMode: "strict"
        # doesn't seem to work with the current go module name?
        # allow:
        #   - "$gostd"
        #   - "constants"
        #   - "github.com/google/uuid"
        #   - "github.com/teambition/rrule-go"
        #   - "finance-planner-tui/constants"
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
      Test:
        files:
          - "$test"
        listMode: "lax"
        deny:
          - pkg: "github.com/stretchr/testify"
            desc: "Please use standard library for tests"
